language: node_js
node_js: lts/*
script:
  - npm run build:package
  - npm run test:package
after_success:
  - npm run coveralls
deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx semantic-release
  on:
    branch: master
